# Generated by Django 5.2.5 on 2026-03-19 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'library',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(600)])),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.library')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='core.song')),
            ],
            options={
                'db_table': 'share_link',
            },
        ),
        migrations.CreateModel(
            name='SongParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('romantic_event', 'Romantic Event'), ('graduation', 'Graduation'), ('other', 'Other')], max_length=20)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('other', 'Other')], max_length=20)),
                ('voice_type', models.CharField(choices=[('baby', 'Baby'), ('grown_woman', 'Grown Woman'), ('grown_man', 'Grown Man'), ('girl', 'Girl'), ('boy', 'Boy')], max_length=20)),
                ('custom_text', models.TextField(blank=True, default='')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.song')),
            ],
            options={
                'db_table': 'song_parameters',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('birthday', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.user')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='core.user'),
        ),
    ]
