# Generated by Django 5.2.5 on 2026-03-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
    ]
