# Generated by Django 5.2.5 on 2026-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='provider',
            field=models.CharField(default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='provider_generation_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
