# Generated by Django 5.2.5 on 2026-04-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='callback_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
