# Generated by Django 5.2.5 on 2026-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_song_embeds_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='generating', max_length=20),
        ),
    ]
