"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_simple_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_simple_env_file(BASE_DIR / '.env')


def _join_public_url(base_url, path):
    if not base_url:
        return ''

    parsed = urlsplit(base_url.strip())
    if not parsed.scheme or not parsed.netloc:
        return ''

    normalized_path = path if path.startswith('/') else f'/{path}'
    return urlunsplit((parsed.scheme, parsed.netloc, normalized_path, '', ''))


def _looks_like_placeholder_callback(url):
    if not url:
        return True

    parsed = urlsplit(url.strip())
    hostname = (parsed.hostname or '').lower()
    if not hostname:
        return True

    return (
        hostname in {'example.com', 'localhost', '127.0.0.1'}
        or hostname.endswith('.example')
        or 'example.' in hostname
        or hostname.endswith('.local')
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b1rc^!3byg*p1v-s=l_kf9&!k&*)uhb2vv-4f6p79xhy#^=#&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = (
    [h.strip() for h in _ALLOWED_HOSTS_ENV.split(',') if h.strip()]
    if _ALLOWED_HOSTS_ENV
    else ['*']
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MUSIC_GENERATION_PROVIDER = os.getenv('MUSIC_GENERATION_PROVIDER', 'mock')
SUNO_API_URL = os.getenv('SUNO_API_URL', '')
SUNO_API_KEY = os.getenv('SUNO_API_KEY', '')
BACKEND_PUBLIC_URL = os.getenv('BACKEND_PUBLIC_URL', '').strip()
_EXPLICIT_SUNO_CALLBACK_URL = os.getenv('SUNO_CALLBACK_URL', '').strip()
SUNO_CALLBACK_URL = (
    _EXPLICIT_SUNO_CALLBACK_URL
    if _EXPLICIT_SUNO_CALLBACK_URL and not _looks_like_placeholder_callback(_EXPLICIT_SUNO_CALLBACK_URL)
    else _join_public_url(BACKEND_PUBLIC_URL, '/integrations/suno/callback/')
)
SUNO_MODEL = os.getenv('SUNO_MODEL', 'V4_5ALL')
SUNO_CUSTOM_MODE = os.getenv('SUNO_CUSTOM_MODE', 'false').lower() == 'true'
SUNO_INSTRUMENTAL = os.getenv('SUNO_INSTRUMENTAL', 'false').lower() == 'true'

GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')
GOOGLE_OAUTH_REDIRECT_URI = os.getenv('GOOGLE_OAUTH_REDIRECT_URI', '')
GOOGLE_OAUTH_AUTH_URI = os.getenv('GOOGLE_OAUTH_AUTH_URI', 'https://accounts.google.com/o/oauth2/v2/auth')
GOOGLE_OAUTH_TOKEN_URI = os.getenv('GOOGLE_OAUTH_TOKEN_URI', 'https://oauth2.googleapis.com/token')
GOOGLE_OAUTH_USERINFO_URI = os.getenv('GOOGLE_OAUTH_USERINFO_URI', 'https://openidconnect.googleapis.com/v1/userinfo')
GOOGLE_OAUTH_SCOPES = os.getenv('GOOGLE_OAUTH_SCOPES', 'openid email profile').split()
FRONTEND_APP_URL = os.getenv('FRONTEND_APP_URL', 'http://127.0.0.1:5173')
